name: app_usages
description: "A new Flutter project."
version: 0.0.1
homepage: 'https://github.com/studio-winpark/app_usages'

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      android:
        package: studio.winpark.app_usages
        pluginClass: AppUsagesPlugin
